version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
  
  #No need as build copys artifact
  #post_build:
            #commands:
              # copy the contents of /build to S3
              #- aws s3 cp --recursive --acl public-read --debug ./build s3://personalpagestorage/PersonalPage
    
artifacts:
  files:
    - '**/*'